version: '3.7'

services:
  app:
    image: xepelin-challenge-app
    container_name: xepelin-challenge-app
    build:
      context: .
    command: bash -c "./scripts/wait-for.sh -t 10 xepelin-rabbitmq:5672 -- npm run start"
    ports:
      - 8080:8080
    volumes:
      - ./input:/xepelin/app/input
      - ./tmp/app-data/logs:/xepelin/app/logs
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=local
      - RABBITMQ_URL=amqp://xepelin-rabbitmq
      - ENDPOINT_DYNAMO=http://xepelin-dynamo:8000
      - IS_DIST=true
      - DB_HOST=xepelin-db
      - DB_PORT=5432
      - DB_USERNAME=businessman
      - DB_PASSWORD=mybusiness
      - DB=business
      - CSV_SPLIT_LIMIT=300
      - CHUNK_WORKER_CRON=*/1 * * * *

networks:
  default:
    external:
      name: xepelin-shared-network
